excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://Pelice.github.io
title: Marco De Fanti logs
tagline: A log of everyday life
description: Appunti vari di un programmatore smanettone
paginate: 5
highlighter: rouge
